#pragma once

#define SHADER_PROGRAM_DEFAULT 0
#define SHADER_PROGRAM_SKYBOX 1
#define SHADER_PROGRAM_LGHTPASS 2
#define SHADER_PROGRAM_BLUR 3
#define SHADER_PROGRAM_BLEND 4
#define SHADER_PROGRAM_DEPTH 5

#define OFF_TEXTURE_BASE 0
#define OFF_TEXTURE_BLURPASSHORIZONTAL 1
#define OFF_TEXTURE_BLURPASSVERTICAL 2
#define OFF_TEXTURE_LIGHTPASS 3
#define OFF_TEXTURE_BLEND 4
#define OFF_TEXTURE_DEPTH 5

#define TEXTURE_OBJECT 0

#define CUBE_MAP_MOUNTAIN 0

#define BLUR_RADIUS 300.0f
#define BLUR_WEIGHT 0.0f

#define ROTATE_SPEED 1.5f